language: node_js
node_js: 10
branches:
  only:
  - master
before_install:
- git remote set-branches --add origin source
- git remote update
- git checkout -b source --track origin/source
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- cd themes/noise
- git remote update
- git reset --hard origin/master
- cd ../..
- hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "${GH_TOKEN}"
  local_dir: public
  on:
    branch: master
env:
  global:
    secure: DJrplKhPYoQC1u9KVaH+lvywTQrmK6OsnsptxB5NUPjdZUn/mgGFOWzdujLcmxDAknFrIx4lH19AmN04Xz0TIDqUghcRtNn0jbPLjq1HLO6sLGQr+qestQP3ri4hSNMoN3LS8zzgnJKrfkV7Uq23++7bjuASQcjGdhCxpREqU1I+VN25whsuMZFIDOwgbGaWi4J/yCppMMKdt/gpHhEfPtyyqfZRGeSMfW8KDEMpF8d88uAaAmsS6sblziJUgPzCAaZDJrXcU3RGAAMMVOlwUY3Ovqq+veBbAqW4vEV2XWS9+vnBLyDcLE8OIyUxEXsDCzP2ihf58WW64imducTOAVNwGqQEjKWzCh2QrZFQALyPmVk1lsloIAIxaCL/UjiKmiyxazYrCh1rXDuglarljJ7iuE+QmVfybLFV06e7eTpePpGtM3o4QCsqxrVm92VnLV4qDeo1xdr8I4cdNybYN5AHGD9R4cvtz0lzgQ+WZeYEJqzhYdI4OafN16OKwv1b6scGHz0CMLp4eGumoDzN0SBOebaUG93w7637oM5NcqXCOXgixHlN6N6yO4XJZW5Czv+lUIdY1/5nxzgdCYZj3nRbgyba042yKL/wEto0cMKdWJ9ylAumnj41d4XRwx8FrfiM+ojoTqKs0J4ZvoNLilwOA/l/XR+oCSBEt2Lxsek=
