language: node_js
node_js:
- '6.0.0'
branches:
  only:
  - master
before_install:
- git remote set-branches --add origin source
- git remote update
- git checkout -b source --track origin/source
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- cd themes/noise
- git remote update
- git reset --hard origin/master
- cd ../..
- hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "${GH_TOKEN}"
  local_dir: public
  on:
    branch: master
